spring:
  application:
    name: medicopilot-backend

  mongodb:
    uri: mongodb://localhost:27017/medicopilot
    database: medicopilot

  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  main:
    web-application-type: reactive

app:
  mri-storage-path: ${MRI_STORAGE_PATH:./uploads/mri}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

